// const tickers = [
//   "Exxon Mobil, XOM",
//   "Apple, AAPL",
//   "Berkshire Hathaway, BRK.B",
//   "McKesson, MCK",
//   "UnitedHealth Group, UNH",
//   "CVS Health, CVS",
//   "General Motors, GM",
//   "Ford Motor, F",
//   "AT&T, T",
//   "General Electric, GE",
//   "AmerisourceBergen, ABC",
//   "Verizon, VZ",
//   "Chevron, CVX",
//   "Costco, COST",
//   "Fannie Mae, FNMA",
//   "Kroger, KR",
//   "Amazon.com, AMZN",
//   "Walgreens, WAG",
//   "HP, HPQ",
//   "Cardinal Health, CAH",
//   "Express Scripts Holding, ESRX",
//   "J.P. Morgan Chase, JPM",
//   "Boeing, BA",
//   "Microsoft, MSFT",
//   "Bank of America Corp., BAC",
//   "Wells Fargo, WFC",
//   "Home Depot, HD",
//   "Citigroup, C",
//   "Phillips 66, PSX",
//   "IBM, IBM",
//   "Valero Energy, VLO",
//   "Anthem, ANTM",
//   "Procter & Gamble, PG",
//   "State Farm Insurance Cos., STFGX",
//   "Google, GOOGL",
//   "Comcast, CMCSA",
//   "Target, TGT",
//   "Johnson & Johnson, JNJ",
//   "MetLife, MET",
//   "Archer Daniels Midland, ADM",
//   "Marathon Petroleum, MPC",
//   "Freddie Mac, FMCC",
//   "PepsiCo, PEP",
//   "United Technologies, UTX",
//   "Aetna, AET",
//   "Lowe's, LOW",
//   "UPS, UPS",
//   "AIG, AIG",
//   "Prudential Financial, PRU",
//   "Intel, INTC",
//   "Humana, HUM",
//   "Disney, DIS",
//   "Cisco Systems, CSCO",
//   "Pfizer, PFE",
//   "Dow Chemical, DOW",
//   "Sysco, SYY",
//   "FedEx, FDX",
//   "Caterpillar, CAT",
//   "Lockheed Martin, LMT",
//   "New York Life Insurance, ",
//   "Coca-Cola, KO",
//   "HCA Holdings, HCA",
//   "Ingram Micro, IM",
//   "Energy Transfer Equity, ETE",
//   "Tyson Foods, TSN",
//   "American Airlines Group, AAL",
//   "Delta Air Lines, DAL",
//   "Nationwide, ",
//   "Johnson Controls, JCI",
//   "Best Buy, BBY",
//   "Merck, MRK",
//   "Liberty Mutual Insurance Group, ",
//   "Goldman Sachs Group, GS",
//   "Honeywell International, HON",
//   "Massachusetts Mutual Life Insurance, ",
//   "Oracle, ORCL",
//   "Morgan Stanley, MS",
//   "Cigna, CI",
//   "United Continental Holdings, UAL",
//   "Allstate, ALL",
//   "TIAA, ",
//   "INTL FCStone, INTL",
//   "CHS, CHS",
//   "American Express, AXP",
//   "Gilead Sciences, GILD",
//   "Publix Super Markets, ",
//   "General Dynamics, GD",
//   "TJX, TJX",
//   "ConocoPhillips, COP",
//   "Nike, NKE",
//   "World Fuel Services, INT",
//   "3M, MMM",
//   "Mondelez International, MDLZ",
//   "Exelon, EXC",
//   "Twenty-First Century Fox, FOXA",
//   "Deere, DE",
//   "Tesoro, TSO",
//   "Time Warner, TWX",
//   "Northwestern Mutual, ",
//   "DuPont, DD",
//   "Avnet, AVT",
//   "Macy's, M",
//   "Enterprise Products Partners, EPD",
//   "Travelers Cos., TRV",
//   "Philip Morris International, PM",
//   "Rite Aid, RAD",
//   "Tech Data, TECD",
//   "McDonald's, MCD",
//   "Qualcomm, QCOM",
//   "Sears Holdings, SHLD",
//   "Capital One Financial, COF",
//   "EMC, EMC",
//   "USAA, ",
//   "Duke Energy, DUK",
//   "Time Warner Cable, TWC",
//   "Halliburton, HAL",
//   "Northrop Grumman, NOC",
//   "Arrow Electronics, ARW",
//   "Raytheon, RTN",
//   "Plains GP Holdings, PAGP",
//   "US Foods, ",
//   "AbbVie, ABBV",
//   "Centene, CNC",
//   "Community Health Systems, CYH",
//   "Arconic, ARNC",
//   "International Paper, IP",
//   "Emerson Electric, EMR",
//   "Union Pacific, UNP",
//   "Amgen, AMGN",
//   "U.S. Bancorp, USB",
//   "Staples, SPLS",
//   "Danaher, DHR",
//   "Whirlpool, WHR",
//   "Aflac, AFL",
//   "AutoNation, AN",
//   "Progressive, PGR",
//   "Abbott Laboratories, ABT",
//   "Dollar General, DG",
//   "Tenet Healthcare, THC",
//   "Eli Lilly, LLY",
//   "Southwest Airlines, LUV",
//   "Penske Automotive Group, PAG",
//   "ManpowerGroup, MAN",
//   "Kohl's, KSS",
//   "Starbucks, SBUX",
//   "Paccar, PCAR",
//   "Cummins, CMI",
//   "Altria Group, MO",
//   "Xerox, XRX",
//   "Kimberly-Clark, KMB",
//   "Hartford Financial Services Group, HIG",
//   "Kraft Heinz, KHC",
//   "Lear, LEA",
//   "Fluor, FLR",
//   "AECOM, ACM",
//   "Facebook, FB",
//   "Jabil Circuit, JBL",
//   "CenturyLink, CTL",
//   "Supervalu, SVU",
//   "General Mills, GIS",
//   "Southern, SO",
//   "NextEra Energy, NEE",
//   "Thermo Fisher Scientific, TMO",
//   "American Electric Power, AEP",
//   "PG&E Corp., PCG",
//   "NGL Energy Partners, NGL",
//   "Bristol-Myers Squibb, BMY",
//   "Goodyear Tire & Rubber, G",
//   "Nucor, NUE",
//   "PNC Financial Services Group, PNC",
//   "Health Net, HNT",
//   "Micron Technology, MU",
//   "Colgate-Palmolive, CL",
//   "Freeport-McMoRan, FCX",
//   "ConAgra Foods, CAG",
//   "Gap, GPS",
//   "Baker Hughes, BHI",
//   "Bank of New York Mellon Corp., BK",
//   "Dollar Tree, DLTR",
//   "Whole Foods Market, WFM",
//   "PPG Industries, PPG",
//   "Genuine Parts, GPC",
//   "Icahn Enterprises, IEP",
//   "Performance Food Group, PFGC",
//   "Omnicom Group, OMC",
//   "DISH Network, DISH",
//   "FirstEnergy, FE",
//   "Monsanto, MON",
//   "AES, AES",
//   "CarMax, KMX",
//   "National Oilwell Varco, NO8",
//   "NRG Energy, NRG",
//   "Western Digital, WDC",
//   "Marriott International, MAR",
//   "Office Depot, ODP",
//   "Nordstrom, JWN",
//   "Kinder Morgan, KMI",
//   "Aramark, ARMK",
//   "DaVita, DVA",
//   "Molina Healthcare, MOH",
//   "WellCare Health Plans, WCG",
//   "CBS, CBS",
//   "Visa, V",
//   "Lincoln National, LNC",
//   "Ecolab, ECL",
//   "Kellogg, K",
//   "C.H. Robinson Worldwide, CHRW",
//   "Textron, TXT",
//   "Loews, L",
//   "Illinois Tool Works, ITW",
//   "Synnex, SNX",
//   "Viacom, VIAB",
//   "HollyFrontier, HFC",
//   "Land O'Lakes, LAKE",
//   "Devon Energy, DVN",
//   "PBF Energy, PBF",
//   "Yum Brands, YUM",
//   "Texas Instruments, TXN",
//   "CDW, CDW",
//   "Waste Management, WM",
//   "Marsh & McLennan, MMC",
//   "Chesapeake Energy, CHK",
//   "Parker-Hannifin, PH",
//   "Occidental Petroleum, OXY",
//   "Guardian Life Ins. Co. of America, ",
//   "Farmers Insurance Exchange, ",
//   "J.C. Penney, JCP",
//   "Consolidated Edison, ED",
//   "Cognizant Technology Solutions, CTSH",
//   "VF, VFC",
//   "Ameriprise Financial, AMP",
//   "Computer Sciences, CSC",
//   "L Brands, LB",
//   "Jacobs Engineering Group, JEC",
//   "Principal Financial Group, PFG",
//   "Ross Stores, ROST",
//   "Bed Bath & Beyond, BBBY",
//   "CSX, CSX",
//   "Toys , TOY",
//   "Las Vegas Sands, LVS",
//   "Leucadia National, LUK",
//   "Dominion Resources, D",
//   "United States Steel, X",
//   "L-3 Communications, LLL",
//   "Edison International, EIX",
//   "Entergy, ELA",
//   "ADP, ADP",
//   "First Data, FDC",
//   "BlackRock, BLK",
//   "WestRock, WRK",
//   "Voya Financial, VOYA",
//   "Sherwin-Williams, SHW",
//   "Hilton Worldwide Holdings, HLT",
//   "R.R. Donnelley & Sons, RRD",
//   "Stanley Black & Decker, SWK",
//   "Xcel Energy, XEL",
//   "Murphy USA, MUSA",
//   "CBRE Group, CBG",
//   "D.R. Horton, DHI",
//   "Estee Lauder, EL",
//   "Praxair, PX",
//   "Biogen, BIIB",
//   "State Street Corp., STT",
//   "Unum Group, UNM",
//   "Reynolds American, RAI",
//   "Group 1 Automotive, GPI",
//   "Henry Schein, HSIC",
//   "Hertz Global Holdings, HRI",
//   "Norfolk Southern, NSC",
//   "Reinsurance Group of America, RGA",
//   "Public Service Enterprise Group, PEG",
//   "BB&T Corp., BBT",
//   "DTE Energy, DTE",
//   "Assurant, AIZ",
//   "Global Partners, GLP",
//   "Huntsman, HUN",
//   "Becton Dickinson, BDX",
//   "Sempra Energy, SRE",
//   "AutoZone, AZO",
//   "Navistar International, NAV",
//   "Precision Castparts, PCP",
//   "Discover Financial Services, DFS",
//   "Liberty Interactive, QVCA",
//   "W.W. Grainger, GWW",
//   "Baxter International, BAX",
//   "Stryker, SYK",
//   "Air Products & Chemicals, APD",
//   "Western Refining, WNR",
//   "Universal Health Services, UHS",
//   "Owens & Minor, OMI",
//   "Charter Communications, CHTR",
//   "Advance Auto Parts, AAP",
//   "MasterCard, MA",
//   "Applied Materials, AMAT",
//   "Eastman Chemical, EMN",
//   "Sonic Automotive, SAH",
//   "Ally Financial, ALLY",
//   "CST Brands, CST",
//   "eBay, EBAY",
//   "Lennar, LEN",
//   "GameStop, GME",
//   "Reliance Steel & Aluminum, RS",
//   "Hormel Foods, HRL",
//   "Celgene, CELG",
//   "Genworth Financial, GNW",
//   "PayPal Holdings, PYPL",
//   "Priceline Group, PCLN",
//   "MGM Resorts International, MGM",
//   "Autoliv, ALV",
//   "Fidelity National Financial, FNF",
//   "Republic Services, RSG",
//   "Corning, GLW",
//   "Peter Kiewit Sons', ",
//   "Univar, UNVR",
//   "Mosaic, MOS",
//   "Core-Mark Holding, CORE",
//   "Thrivent Financial for Lutherans, ",
//   "Cameron International, CAM",
//   "HD Supply Holdings, HDS",
//   "Crown Holdings, CCK",
//   "EOG Resources, EOG",
//   "Veritiv, VRTV",
//   "Anadarko Petroleum, APC",
//   "Laboratory Corp. of America, LH",
//   "Pacific Life, ",
//   "News Corp., FOXA",
//   "Jarden, JAH",
//   "SunTrust Banks, STI",
//   "Avis Budget Group, CAR",
//   "Broadcom, BRCM",
//   "American Family Insurance Group, ",
//   "Level 3 Communications, LVLT",
//   "Tenneco, TEN",
//   "United Natural Foods, UNFI",
//   "Dean Foods, DF",
//   "Campbell Soup, CPB",
//   "Mohawk Industries, MHK",
//   "BorgWarner, BWA",
//   "PVH, PVH",
//   "Ball, BLL",
//   "O'Reilly Automotive, ORLY",
//   "Eversource Energy, ES",
//   "Franklin Resources, BEN",
//   "Masco, MAS",
//   "Lithia Motors, LAD",
//   "KKR, KKR",
//   "Oneok, OKE",
//   "Newmont Mining, NEM",
//   "PPL, PPL",
//   "SpartanNash, SPTN",
//   "Quanta Services, PWR",
//   "XPO Logistics, XPO",
//   "Ralph Lauren, RL",
//   "Interpublic Group, IPG",
//   "Steel Dynamics, STLD",
//   "WESCO International, WCC",
//   "Quest Diagnostics, DGX",
//   "Boston Scientific, BSX",
//   "AGCO, AGCO",
//   "Foot Locker, FL",
//   "Hershey, HSY",
//   "CenterPoint Energy, CNP",
//   "Williams, WMB",
//   "Dick's Sporting Goods, DKS",
//   "Live Nation Entertainment, LYV",
//   "Mutual of Omaha Insurance, ",
//   "W.R. Berkley, WRB",
//   "LKQ, LKQ",
//   "Avon Products, AVP",
//   "Darden Restaurants, DRI",
//   "Kindred Healthcare, KND",
//   "Weyerhaeuser, WY",
//   "Casey's General Stores, CASY",
//   "Sealed Air, SEE",
//   "Fifth Third Bancorp, FITB",
//   "Dover, DOV",
//   "Huntington Ingalls Industries, HII",
//   "Netflix, NFLX",
//   "Dillard's, DDS",
//   "EMCOR Group, EME",
//   "Jones Financial, JONE",
//   "AK Steel Holding, AKS",
//   "UGI, UGI",
//   "Expedia, EXPE",
//   "salesforce.com, CRM",
//   "Targa Resources, TRGP",
//   "Apache, APA",
//   "Spirit AeroSystems Holdings, SPR",
//   "Expeditors International of Washington, EXPD",
//   "Anixter International, AXE",
//   "Fidelity National Information Services, FIS",
//   "Asbury Automotive Group, ABG",
//   "Hess, HES",
//   "Ryder System, R",
//   "Terex, TEX",
//   "Coca-Cola European Partners, ",
//   "Auto-Owners Insurance, ",
//   "Cablevision Systems, CVC",
//   "Symantec, SYMC",
//   "Charles Schwab, SCHW",
//   "Calpine, CPN",
//   "CMS Energy, CMS",
//   "Alliance Data Systems, ADS",
//   "JetBlue Airways, JBLU",
//   "Discovery Communications, DISCA",
//   "Trinity Industries, TRN",
//   "Sanmina, SANM",
//   "NCR, NCR",
//   "FMC Technologies, FTI",
//   "Erie Insurance Group, ERIE",
//   "Rockwell Automation, ROK",
//   "Dr Pepper Snapple Group, DPS",
//   "iHeartMedia, IHRT",
//   "Tractor Supply, TSCO",
//   "J.B. Hunt Transport Services, JBHT",
//   "Commercial Metals, CMC",
//   "Owens-Illinois, OI",
//   "Harman International Industries, HAR",
//   "Baxalta, BXLT",
//   "American Financial Group, AFG",
//   "NetApp, NTAP",
//   "Graybar Electric, ",
//   "Oshkosh, OSK",
//   "Ameren, AEE",
//   "A-Mark Precious Metals, AMRK",
//   "Barnes & Noble, BKS",
//   "Dana Holding, DAN",
//   "Constellation Brands, STZ",
//   "LifePoint Health, LPNT",
//   "Zimmer Biomet Holdings, ZBH",
//   "Harley-Davidson, HOG",
//   "PulteGroup, PHM",
//   "Newell Brands, NWL",
//   "Avery Dennison, AVY",
//   "Jones Lang LaSalle, JLL",
//   "WEC Energy Group, WEC",
//   "Marathon Oil, MRO",
//   "TravelCenters of America, TA",
//   "United Rentals, URI",
//   "HRG Group, HRG",
//   "Old Republic International, ORI",
//   "Windstream Holdings, WIN",
//   "Starwood Hotels & Resorts, HOT",
//   "Delek US Holdings, DK",
//   "Packaging Corp. of America, PKG",
//   "Quintiles IMS Holdings, Q",
//   "Hanesbrands, HBI",
//   "Realogy Holdings, RLGY",
//   "Mattel, MAT",
//   "Motorola Solutions, MSI",
//   "J.M. Smucker, SJM",
//   "Regions Financial, RF",
//   "Celanese, CE",
//   "Clorox, CLX",
//   "Ingredion, INGR",
//   "Genesis Healthcare, GEN",
//   "Peabody Energy, BTU",
//   "Alaska Air Group, ALK",
//   "Seaboard, SEB",
//   "Frontier Communications, FTR",
//   "Amphenol, APH",
//   "Lansing Trade Group, ",
//   "SanDisk, SNDK",
//   "St. Jude Medical, STJ",
//   "Wyndham Worldwide, WYN",
//   "Kelly Services, KELYA",
//   "Western Union, WU",
//   "Envision Healthcare Holdings, ",
//   "Visteon, VC",
//   "Arthur J. Gallagher, AJG",
//   "Host Hotels & Resorts, HST",
//   "Ashland, ASH",
//   "Insight Enterprises, NSIT",
//   "Energy Future Holdings, ",
//   "Markel, MKL",
//   "Essendant, ESND",
//   "CH2M Hill, ",
//   "Western & Southern Financial Group, ",
//   "Owens Corning, OC",
//   "S&P Global, SPGI",
//   "Raymond James Financial, RJF",
//   "NiSource, NI",
//   "Airgas, ARG",
//   "ABM Industries, ABM",
//   "Citizens Financial Group, CFG",
//   "Booz Allen Hamilton Holding, BAH",
//   "Simon Property Group, SPGI",
//   "Domtar, UFS",
//   "Rockwell Collins, COL",
//   "Lam Research, LRCX",
//   "Fiserv, FISV",
//   "Spectra Energy, SE",
//   "Navient, NAVI",
//   "Big Lots, BIG",
//   "Telephone & Data Systems, TDS",
//   "First American Financial, FAF",
//   "NVR, NVR",
//   "Cincinnati Financial, CINF",
//   "Burlington Stores, BURL"
// ];



const tickers = [
    {company: "Exxon Mobil, XOM"},
    {company: "Apple, AAPL"},
    {company: "Berkshire Hathaway, BRK.B"},
    {company: "McKesson, MCK"},
    {company: "UnitedHealth Group, UNH"},
    {company: "CVS Health, CVS"},
    {company: "General Motors, GM"},
    {company: "Ford Motor, F"},
    {company: "AT&T, T"},
    {company: "General Electric, GE"},
    {company: "AmerisourceBergen, ABC"},
    {company: "Verizon, VZ"},
    {company: "Chevron, CVX"},
    {company: "Costco, COST"},
    {company: "Fannie Mae, FNMA"},
    {company: "Kroger, KR"},
    {company: "Amazon.com, AMZN"},
    {company: "Walgreens, WAG"},
    {company: "HP, HPQ"},
    {company: "Cardinal Health, CAH"},
    {company: "Express Scripts Holding, ESRX"},
    {company: "J.P. Morgan Chase, JPM"},
    {company: "Boeing, BA"},
    {company: "Microsoft, MSFT"},
    {company: "Bank of America Corp., BAC"},
    {company: "Wells Fargo, WFC"},
    {company: "Home Depot, HD"},
    {company: "Citigroup, C"},
    {company: "Phillips 66, PSX"},
    {company: "IBM, IBM"},
    {company: "Valero Energy, VLO"},
    {company: "Anthem, ANTM"},
    {company: "Procter & Gamble, PG"},
    {company: "State Farm Insurance Cos., STFGX"},
    {company: "Google, GOOGL"},
    {company: "Comcast, CMCSA"},
    {company: "Target, TGT"},
    {company: "Johnson & Johnson, JNJ"},
    {company: "MetLife, MET"},
    {company: "Archer Daniels Midland, ADM"},
    {company: "Marathon Petroleum, MPC"},
    {company: "Freddie Mac, FMCC"},
    {company: "PepsiCo, PEP"},
    {company: "United Technologies, UTX"},
    {company: "Aetna, AET"},
    {company: "Lowe's, LOW"},
    {company: "UPS, UPS"},
    {company: "AIG, AIG"},
    {company: "Prudential Financial, PRU"},
    {company: "Intel, INTC"},
    {company: "Humana, HUM"},
    {company: "Disney, DIS"},
    {company: "Cisco Systems, CSCO"},
    {company: "Pfizer, PFE"},
    {company: "Dow Chemical, DOW"},
    {company: "Sysco, SYY"},
    {company: "FedEx, FDX"},
    {company: "Caterpillar, CAT"},
    {company: "Lockheed Martin, LMT"},
    {company: "New York Life Insurance, "},
    {company: "Coca-Cola, KO"},
    {company: "HCA Holdings, HCA"},
    {company: "Ingram Micro, IM"},
    {company: "Energy Transfer Equity, ETE"},
    {company: "Tyson Foods, TSN"},
    {company: "American Airlines Group, AAL"},
    {company: "Delta Air Lines, DAL"},
    {company: "Nationwide, "},
    {company: "Johnson Controls, JCI"},
    {company: "Best Buy, BBY"},
    {company: "Merck, MRK"},
    {company: "Liberty Mutual Insurance Group, "},
    {company: "Goldman Sachs Group, GS"},
    {company: "Honeywell International, HON"},
    {company: "Massachusetts Mutual Life Insurance, "},
    {company: "Oracle, ORCL"},
    {company: "Morgan Stanley, MS"},
    {company: "Cigna, CI"},
    {company: "United Continental Holdings, UAL"},
    {company: "Allstate, ALL"},
    {company: "TIAA, "},
    {company: "INTL FCStone, INTL"},
    {company: "CHS, CHS"},
    {company: "American Express, AXP"},
    {company: "Gilead Sciences, GILD"},
    {company: "Publix Super Markets, "},
    {company: "General Dynamics, GD"},
    {company: "TJX, TJX"},
    {company: "ConocoPhillips, COP"},
    {company: "Nike, NKE"},
    {company: "World Fuel Services, INT"},
    {company: "3M, MMM"},
    {company: "Mondelez International, MDLZ"},
    {company: "Exelon, EXC"},
    {company: "Twenty-First Century Fox, FOXA"},
    {company: "Deere, DE"},
    {company: "Tesoro, TSO"},
    {company: "Time Warner, TWX"},
    {company: "Northwestern Mutual, "},
    {company: "DuPont, DD"},
    {company: "Avnet, AVT"},
    {company: "Macy's, M"},
    {company: "Enterprise Products Partners, EPD"},
    {company: "Travelers Cos., TRV"},
    {company: "Philip Morris International, PM"},
    {company: "Rite Aid, RAD"},
    {company: "Tech Data, TECD"},
    {company: "McDonald's, MCD"},
    {company: "Qualcomm, QCOM"},
    {company: "Sears Holdings, SHLD"},
    {company: "Capital One Financial, COF"},
    {company: "EMC, EMC"},
    {company: "USAA, "},
    {company: "Duke Energy, DUK"},
    {company: "Time Warner Cable, TWC"},
    {company: "Halliburton, HAL"},
    {company: "Northrop Grumman, NOC"},
    {company: "Arrow Electronics, ARW"},
    {company: "Raytheon, RTN"},
    {company: "Plains GP Holdings, PAGP"},
    {company: "US Foods, "},
    {company: "AbbVie, ABBV"},
    {company: "Centene, CNC"},
    {company: "Community Health Systems, CYH"},
    {company: "Arconic, ARNC"},
    {company: "International Paper, IP"},
    {company: "Emerson Electric, EMR"},
    {company: "Union Pacific, UNP"},
    {company: "Amgen, AMGN"},
    {company: "U.S. Bancorp, USB"},
    {company: "Staples, SPLS"},
    {company: "Danaher, DHR"},
    {company: "Whirlpool, WHR"},
    {company: "Aflac, AFL"},
    {company: "AutoNation, AN"},
    {company: "Progressive, PGR"},
    {company: "Abbott Laboratories, ABT"},
    {company: "Dollar General, DG"},
    {company: "Tenet Healthcare, THC"},
    {company: "Eli Lilly, LLY"},
    {company: "Southwest Airlines, LUV"},
    {company: "Penske Automotive Group, PAG"},
    {company: "ManpowerGroup, MAN"},
    {company: "Kohl's, KSS"},
    {company: "Starbucks, SBUX"},
    {company: "Paccar, PCAR"},
    {company: "Cummins, CMI"},
    {company: "Altria Group, MO"},
    {company: "Xerox, XRX"},
    {company: "Kimberly-Clark, KMB"},
    {company: "Hartford Financial Services Group, HIG"},
    {company: "Kraft Heinz, KHC"},
    {company: "Lear, LEA"},
    {company: "Fluor, FLR"},
    {company: "AECOM, ACM"},
    {company: "Facebook, FB"},
    {company: "Jabil Circuit, JBL"},
    {company: "CenturyLink, CTL"},
    {company: "Supervalu, SVU"},
    {company: "General Mills, GIS"},
    {company: "Southern, SO"},
    {company: "NextEra Energy, NEE"},
    {company: "Thermo Fisher Scientific, TMO"},
    {company: "American Electric Power, AEP"},
    {company: "PG&E Corp., PCG"},
    {company: "NGL Energy Partners, NGL"},
    {company: "Bristol-Myers Squibb, BMY"},
    {company: "Goodyear Tire & Rubber, G"},
    {company: "Nucor, NUE"},
    {company: "PNC Financial Services Group, PNC"},
    {company: "Health Net, HNT"},
    {company: "Micron Technology, MU"},
    {company: "Colgate-Palmolive, CL"},
    {company: "Freeport-McMoRan, FCX"},
    {company: "ConAgra Foods, CAG"},
    {company: "Gap, GPS"},
    {company: "Baker Hughes, BHI"},
    {company: "Bank of New York Mellon Corp., BK"},
    {company: "Dollar Tree, DLTR"},
    {company: "Whole Foods Market, WFM"},
    {company: "PPG Industries, PPG"},
    {company: "Genuine Parts, GPC"},
    {company: "Icahn Enterprises, IEP"},
    {company: "Performance Food Group, PFGC"},
    {company: "Omnicom Group, OMC"},
    {company: "DISH Network, DISH"},
    {company: "FirstEnergy, FE"},
    {company: "Monsanto, MON"},
    {company: "AES, AES"},
    {company: "CarMax, KMX"},
    {company: "National Oilwell Varco, NO8"},
    {company: "NRG Energy, NRG"},
    {company: "Western Digital, WDC"},
    {company: "Marriott International, MAR"},
    {company: "Office Depot, ODP"},
    {company: "Nordstrom, JWN"},
    {company: "Kinder Morgan, KMI"},
    {company: "Aramark, ARMK"},
    {company: "DaVita, DVA"},
    {company: "Molina Healthcare, MOH"},
    {company: "WellCare Health Plans, WCG"},
    {company: "CBS, CBS"},
    {company: "Visa, V"},
    {company: "Lincoln National, LNC"},
    {company: "Ecolab, ECL"},
    {company: "Kellogg, K"},
    {company: "C.H. Robinson Worldwide, CHRW"},
    {company: "Textron, TXT"},
    {company: "Loews, L"},
    {company: "Illinois Tool Works, ITW"},
    {company: "Synnex, SNX"},
    {company: "Viacom, VIAB"},
    {company: "HollyFrontier, HFC"},
    {company: "Land O'Lakes, LAKE"},
    {company: "Devon Energy, DVN"},
    {company: "PBF Energy, PBF"},
    {company: "Yum Brands, YUM"},
    {company: "Texas Instruments, TXN"},
    {company: "CDW, CDW"},
    {company: "Waste Management, WM"},
    {company: "Marsh & McLennan, MMC"},
    {company: "Chesapeake Energy, CHK"},
    {company: "Parker-Hannifin, PH"},
    {company: "Occidental Petroleum, OXY"},
    {company: "Guardian Life Ins. Co. of America, "},
    {company: "Farmers Insurance Exchange, "},
    {company: "J.C. Penney, JCP"},
    {company: "Consolidated Edison, ED"},
    {company: "Cognizant Technology Solutions, CTSH"},
    {company: "VF, VFC"},
    {company: "Ameriprise Financial, AMP"},
    {company: "Computer Sciences, CSC"},
    {company: "L Brands, LB"},
    {company: "Jacobs Engineering Group, JEC"},
    {company: "Principal Financial Group, PFG"},
    {company: "Ross Stores, ROST"},
    {company: "Bed Bath & Beyond, BBBY"},
    {company: "CSX, CSX"},
    {company: "Toys , TOY"},
    {company: "Las Vegas Sands, LVS"},
    {company: "Leucadia National, LUK"},
    {company: "Dominion Resources, D"},
    {company: "United States Steel, X"},
    {company: "L-3 Communications, LLL"},
    {company: "Edison International, EIX"},
    {company: "Entergy, ELA"},
    {company: "ADP, ADP"},
    {company: "First Data, FDC"},
    {company: "BlackRock, BLK"},
    {company: "WestRock, WRK"},
    {company: "Voya Financial, VOYA"},
    {company: "Sherwin-Williams, SHW"},
    {company: "Hilton Worldwide Holdings, HLT"},
    {company: "R.R. Donnelley & Sons, RRD"},
    {company: "Stanley Black & Decker, SWK"},
    {company: "Xcel Energy, XEL"},
    {company: "Murphy USA, MUSA"},
    {company: "CBRE Group, CBG"},
    {company: "D.R. Horton, DHI"},
    {company: "Estee Lauder, EL"},
    {company: "Praxair, PX"},
    {company: "Biogen, BIIB"},
    {company: "State Street Corp., STT"},
    {company: "Unum Group, UNM"},
    {company: "Reynolds American, RAI"},
    {company: "Group 1 Automotive, GPI"},
    {company: "Henry Schein, HSIC"},
    {company: "Hertz Global Holdings, HRI"},
    {company: "Norfolk Southern, NSC"},
    {company: "Reinsurance Group of America, RGA"},
    {company: "Public Service Enterprise Group, PEG"},
    {company: "BB&T Corp., BBT"},
    {company: "DTE Energy, DTE"},
    {company: "Assurant, AIZ"},
    {company: "Global Partners, GLP"},
    {company: "Huntsman, HUN"},
    {company: "Becton Dickinson, BDX"},
    {company: "Sempra Energy, SRE"},
    {company: "AutoZone, AZO"},
    {company: "Navistar International, NAV"},
    {company: "Precision Castparts, PCP"},
    {company: "Discover Financial Services, DFS"},
    {company: "Liberty Interactive, QVCA"},
    {company: "W.W. Grainger, GWW"},
    {company: "Baxter International, BAX"},
    {company: "Stryker, SYK"},
    {company: "Air Products & Chemicals, APD"},
    {company: "Western Refining, WNR"},
    {company: "Universal Health Services, UHS"},
    {company: "Owens & Minor, OMI"},
    {company: "Charter Communications, CHTR"},
    {company: "Advance Auto Parts, AAP"},
    {company: "MasterCard, MA"},
    {company: "Applied Materials, AMAT"},
    {company: "Eastman Chemical, EMN"},
    {company: "Sonic Automotive, SAH"},
    {company: "Ally Financial, ALLY"},
    {company: "CST Brands, CST"},
    {company: "eBay, EBAY"},
    {company: "Lennar, LEN"},
    {company: "GameStop, GME"},
    {company: "Reliance Steel & Aluminum, RS"},
    {company: "Hormel Foods, HRL"},
    {company: "Celgene, CELG"},
    {company: "Genworth Financial, GNW"},
    {company: "PayPal Holdings, PYPL"},
    {company: "Priceline Group, PCLN"},
    {company: "MGM Resorts International, MGM"},
    {company: "Autoliv, ALV"},
    {company: "Fidelity National Financial, FNF"},
    {company: "Republic Services, RSG"},
    {company: "Corning, GLW"},
    {company: "Peter Kiewit Sons', "},
    {company: "Univar, UNVR"},
    {company: "Mosaic, MOS"},
    {company: "Core-Mark Holding, CORE"},
    {company: "Thrivent Financial for Lutherans, "},
    {company: "Cameron International, CAM"},
    {company: "HD Supply Holdings, HDS"},
    {company: "Crown Holdings, CCK"},
    {company: "EOG Resources, EOG"},
    {company: "Veritiv, VRTV"},
    {company: "Anadarko Petroleum, APC"},
    {company: "Laboratory Corp. of America, LH"},
    {company: "Pacific Life, "},
    {company: "News Corp., FOXA"},
    {company: "Jarden, JAH"},
    {company: "SunTrust Banks, STI"},
    {company: "Avis Budget Group, CAR"},
    {company: "Broadcom, BRCM"},
    {company: "American Family Insurance Group, "},
    {company: "Level 3 Communications, LVLT"},
    {company: "Tenneco, TEN"},
    {company: "United Natural Foods, UNFI"},
    {company: "Dean Foods, DF"},
    {company: "Campbell Soup, CPB"},
    {company: "Mohawk Industries, MHK"},
    {company: "BorgWarner, BWA"},
    {company: "PVH, PVH"},
    {company: "Ball, BLL"},
    {company: "O'Reilly Automotive, ORLY"},
    {company: "Eversource Energy, ES"},
    {company: "Franklin Resources, BEN"},
    {company: "Masco, MAS"},
    {company: "Lithia Motors, LAD"},
    {company: "KKR, KKR"},
    {company: "Oneok, OKE"},
    {company: "Newmont Mining, NEM"},
    {company: "PPL, PPL"},
    {company: "SpartanNash, SPTN"},
    {company: "Quanta Services, PWR"},
    {company: "XPO Logistics, XPO"},
    {company: "Ralph Lauren, RL"},
    {company: "Interpublic Group, IPG"},
    {company: "Steel Dynamics, STLD"},
    {company: "WESCO International, WCC"},
    {company: "Quest Diagnostics, DGX"},
    {company: "Boston Scientific, BSX"},
    {company: "AGCO, AGCO"},
    {company: "Foot Locker, FL"},
    {company: "Hershey, HSY"},
    {company: "CenterPoint Energy, CNP"},
    {company: "Williams, WMB"},
    {company: "Dick's Sporting Goods, DKS"},
    {company: "Live Nation Entertainment, LYV"},
    {company: "Mutual of Omaha Insurance, "},
    {company: "W.R. Berkley, WRB"},
    {company: "LKQ, LKQ"},
    {company: "Avon Products, AVP"},
    {company: "Darden Restaurants, DRI"},
    {company: "Kindred Healthcare, KND"},
    {company: "Weyerhaeuser, WY"},
    {company: "Casey's General Stores, CASY"},
    {company: "Sealed Air, SEE"},
    {company: "Fifth Third Bancorp, FITB"},
    {company: "Dover, DOV"},
    {company: "Huntington Ingalls Industries, HII"},
    {company: "Netflix, NFLX"},
    {company: "Dillard's, DDS"},
    {company: "EMCOR Group, EME"},
    {company: "Jones Financial, JONE"},
    {company: "AK Steel Holding, AKS"},
    {company: "UGI, UGI"},
    {company: "Expedia, EXPE"},
    {company: "salesforce.com, CRM"},
    {company: "Targa Resources, TRGP"},
    {company: "Apache, APA"},
    {company: "Spirit AeroSystems Holdings, SPR"},
    {company: "Expeditors International of Washington, EXPD"},
    {company: "Anixter International, AXE"},
    {company: "Fidelity National Information Services, FIS"},
    {company: "Asbury Automotive Group, ABG"},
    {company: "Hess, HES"},
    {company: "Ryder System, R"},
    {company: "Terex, TEX"},
    {company: "Coca-Cola European Partners, "},
    {company: "Auto-Owners Insurance, "},
    {company: "Cablevision Systems, CVC"},
    {company: "Symantec, SYMC"},
    {company: "Charles Schwab, SCHW"},
    {company: "Calpine, CPN"},
    {company: "CMS Energy, CMS"},
    {company: "Alliance Data Systems, ADS"},
    {company: "JetBlue Airways, JBLU"},
    {company: "Discovery Communications, DISCA"},
    {company: "Trinity Industries, TRN"},
    {company: "Sanmina, SANM"},
    {company: "NCR, NCR"},
    {company: "FMC Technologies, FTI"},
    {company: "Erie Insurance Group, ERIE"},
    {company: "Rockwell Automation, ROK"},
    {company: "Dr Pepper Snapple Group, DPS"},
    {company: "iHeartMedia, IHRT"},
    {company: "Tractor Supply, TSCO"},
    {company: "J.B. Hunt Transport Services, JBHT"},
    {company: "Commercial Metals, CMC"},
    {company: "Owens-Illinois, OI"},
    {company: "Harman International Industries, HAR"},
    {company: "Baxalta, BXLT"},
    {company: "American Financial Group, AFG"},
    {company: "NetApp, NTAP"},
    {company: "Graybar Electric, "},
    {company: "Oshkosh, OSK"},
    {company: "Ameren, AEE"},
    {company: "A-Mark Precious Metals, AMRK"},
    {company: "Barnes & Noble, BKS"},
    {company: "Dana Holding, DAN"},
    {company: "Constellation Brands, STZ"},
    {company: "LifePoint Health, LPNT"},
    {company: "Zimmer Biomet Holdings, ZBH"},
    {company: "Harley-Davidson, HOG"},
    {company: "PulteGroup, PHM"},
    {company: "Newell Brands, NWL"},
    {company: "Avery Dennison, AVY"},
    {company: "Jones Lang LaSalle, JLL"},
    {company: "WEC Energy Group, WEC"},
    {company: "Marathon Oil, MRO"},
    {company: "TravelCenters of America, TA"},
    {company: "United Rentals, URI"},
    {company: "HRG Group, HRG"},
    {company: "Old Republic International, ORI"},
    {company: "Windstream Holdings, WIN"},
    {company: "Starwood Hotels & Resorts, HOT"},
    {company: "Delek US Holdings, DK"},
    {company: "Packaging Corp. of America, PKG"},
    {company: "Quintiles IMS Holdings, Q"},
    {company: "Hanesbrands, HBI"},
    {company: "Realogy Holdings, RLGY"},
    {company: "Mattel, MAT"},
    {company: "Motorola Solutions, MSI"},
    {company: "J.M. Smucker, SJM"},
    {company: "Regions Financial, RF"},
    {company: "Celanese, CE"},
    {company: "Clorox, CLX"},
    {company: "Ingredion, INGR"},
    {company: "Genesis Healthcare, GEN"},
    {company: "Peabody Energy, BTU"},
    {company: "Alaska Air Group, ALK"},
    {company: "Seaboard, SEB"},
    {company: "Frontier Communications, FTR"},
    {company: "Amphenol, APH"},
    {company: "Lansing Trade Group, "},
    {company: "SanDisk, SNDK"},
    {company: "St. Jude Medical, STJ"},
    {company: "Wyndham Worldwide, WYN"},
    {company: "Kelly Services, KELYA"},
    {company: "Western Union, WU"},
    {company: "Envision Healthcare Holdings, "},
    {company: "Visteon, VC"},
    {company: "Arthur J. Gallagher, AJG"},
    {company: "Host Hotels & Resorts, HST"},
    {company: "Ashland, ASH"},
    {company: "Insight Enterprises, NSIT"},
    {company: "Energy Future Holdings, "},
    {company: "Markel, MKL"},
    {company: "Essendant, ESND"},
    {company: "CH2M Hill, "},
    {company: "Western & Southern Financial Group, "},
    {company: "Owens Corning, OC"},
    {company: "S&P Global, SPGI"},
    {company: "Raymond James Financial, RJF"},
    {company: "NiSource, NI"},
    {company: "Airgas, ARG"},
    {company: "ABM Industries, ABM"},
    {company: "Citizens Financial Group, CFG"},
    {company: "Booz Allen Hamilton Holding, BAH"},
    {company: "Simon Property Group, SPGI"},
    {company: "Domtar, UFS"},
    {company: "Rockwell Collins, COL"},
    {company: "Lam Research, LRCX"},
    {company: "Fiserv, FISV"},
    {company: "Spectra Energy, SE"},
    {company: "Navient, NAVI"},
    {company: "Big Lots, BIG"},
    {company: "Telephone & Data Systems, TDS"},
    {company: "First American Financial, FAF"},
    {company: "NVR, NVR"},
    {company: "Cincinnati Financial, CINF"},
    {company: "Burlington Stores, BURL"}
  ];

//   const tickers = [
//     {company: "Exxon Mobil", symbol: "XOM"},
//     {company: "Apple", symbol: "APPL"},
//     {company: "Berkshire Hathaway", symbol: "BRK.B"},
//     {company: "McKesson", symbol: "MCK"},
//     {company: "UnitedHealth Group", symbol: "UNH"},
//     {company: "CVS Health", symbol: "CVS"},
//     {company: "General Motors", symbol: "GM"},
//     {company: "Ford Motor", symbol: "F"},
//     {company: "AT&T", symbol: "T"},
//     {company: "General Electric", symbol: "GE"},
//     {company: "AmerisourceBergen", symbol: "ABC"},
//     {company: "Verizon", symbol: "VZ"},
//     {company: "Chevron", symbol: "CVX"},
//     {company: "Costco", symbol: "COST"},
//     {company: "Fannie Mae", symbol: "FNMA"},
//     {company: "Kroger", symbol: "KR"},
//     {company: "Amazon.com", symbol: "AMZN"},
//     {company: "Walgreens", symbol: "WAG"},
//     {company: "HP", symbol: "HPQ"},
//     {company: "Cardinal Health", symbol: "CAH"},
//     {company: "Express Scripts Holding", symbol: "ESRX"},
//     {company: "J.P. Morgan Chase", symbol: "JPM"},
//     {company: "Boeing", symbol: "BA"},
//     {company: "Microsoft", symbol: "MSFT"},
//     {company: "Bank of America Corp.", symbol: "BAC"},
//     {company: "Wells Fargo", symbol: "WFC"},
//     {company: "Home Depot", symbol: "HD"},
//     {company: "Citigroup", symbol: "C"},
//     {company: "Phillips 66", symbol: "PSX"},
//     {company: "IBM", symbol: "IBM"},
//     {company: "Valero Energy", symbol: "VLO"},
//     {company: "Anthem", symbol: "ANTM"},
//     {company: "Procter & Gamble", symbol: "PG"},
//     {company: "State Farm Insurance Cos.", symbol: "STFGX"},
//     {company: "Alphabet", symbol: "GOOGL"},
//     {company: "Comcast", symbol: "CMCSA"},
//     {company: "Target", symbol: "TGT"},
//     {company: "Johnson & Johnson", symbol: "JNJ"},
//     {company: "MetLife", symbol: "MET"},
//     {company: "Archer Daniels Midland", symbol: "ADM"},
//     {company: "Marathon Petroleum", symbol: "MPC"},
//     {company: "Freddie Mac", symbol: "FMCC"},
//     {company: "PepsiCo", symbol: "PEP"},
//     {company: "United Technologies", symbol: "UTX"},
//     {company: "Aetna", symbol: "AET"},
//     {company: "Lowe's", symbol: "LOW"},
//     {company: "UPS", symbol: "UPS"},
//     {company: "AIG", symbol: "AIG"},
//     {company: "Prudential Financial", symbol: "PRU"},
//     {company: "Intel", symbol: "INTC"},
//     {company: "Humana", symbol: "HUM"},
//     {company: "Disney", symbol: "DIS"},
//     {company: "Cisco Systems", symbol: "CSCO"},
//     {company: "Pfizer", symbol: "PFE"},
//     {company: "Dow Chemical", symbol: "DOW"},
//     {company: "Sysco", symbol: "SYY"},
//     {company: "FedEx", symbol: "FDX"},
//     {company: "Caterpillar", symbol: "CAT"},
//     {company: "Lockheed Martin", symbol: "LMT"},
//     {company: "New York Life Insurance", symbol: ""},
//     {company: "Coca-Cola", symbol: "KO"},
//     {company: "HCA Holdings", symbol: "HCA"},
//     {company: "Ingram Micro", symbol: "IM"},
//     {company: "Energy Transfer Equity", symbol: "ETE"},
//     {company: "Tyson Foods", symbol: "TSN"},
//     {company: "American Airlines Group", symbol: "AAL"},
//     {company: "Delta Air Lines", symbol: "DAL"},
//     {company: "Nationwide", symbol: ""},
//     {company: "Johnson Controls", symbol: "JCI"},
//     {company: "Best Buy", symbol: "BBY"},
//     {company: "Merck", symbol: "MRK"},
//     {company: "Liberty Mutual Insurance Group", symbol: ""},
//     {company: "Goldman Sachs Group", symbol: "GS"},
//     {company: "Honeywell International", symbol: "HON"},
//     {company: "Massachusetts Mutual Life Insurance", symbol: ""},
//     {company: "Oracle", symbol: "ORCL"},
//     {company: "Morgan Stanley", symbol: "MS"},
//     {company: "Cigna", symbol: "CI"},
//     {company: "United Continental Holdings", symbol: "UAL"},
//     {company: "Allstate", symbol: "ALL"},
//     {company: "TIAA", symbol: ""},
//     {company: "INTL FCStone", symbol: "INTL"},
//     {company: "CHS", symbol: "CHS"},
//     {company: "American Express", symbol: "AXP"},
//     {company: "Gilead Sciences", symbol: "GILD"},
//     {company: "Publix Super Markets", symbol: ""},
//     {company: "General Dynamics", symbol: "GD"},
//     {company: "TJX", symbol: "TJX"},
//     {company: "ConocoPhillips", symbol: "COP"},
//     {company: "Nike", symbol: "NKE"},
//     {company: "World Fuel Services", symbol: "INT"},
//     {company: "3M", symbol: "MMM"},
//     {company: "Mondelez International", symbol: "MDLZ"},
//     {company: "Exelon", symbol: "EXC"},
//     {company: "Twenty-First Century Fox", symbol: "FOXA"},
//     {company: "Deere", symbol: "DE"},
//     {company: "Tesoro", symbol: "TSO"},
//     {company: "Time Warner", symbol: "TWX"},
//     {company: "Northwestern Mutual", symbol: ""},
//     {company: "DuPont", symbol: "DD"},
//     {company: "Avnet", symbol: "AVT"},
//     {company: "Macy's", symbol: "M"},
//     {company: "Enterprise Products Partners", symbol: "EPD"},
//     {company: "Travelers Cos.", symbol: "TRV"},
//     {company: "Philip Morris International", symbol: "PM"},
//     {company: "Rite Aid", symbol: "RAD"},
//     {company: "Tech Data", symbol: "TECD"},
//     {company: "McDonald's", symbol: "MCD"},
//     {company: "Qualcomm", symbol: "QCOM"},
//     {company: "Sears Holdings", symbol: "SHLD"},
//     {company: "Capital One Financial", symbol: "COF"},
//     {company: "EMC", symbol: "EMC"},
//     {company: "USAA", symbol: ""},
//     {company: "Duke Energy", symbol: "DUK"},
//     {company: "Time Warner Cable", symbol: "TWC"},
//     {company: "Halliburton", symbol: "HAL"},
//     {company: "Northrop Grumman", symbol: "NOC"},
//     {company: "Arrow Electronics", symbol: "ARW"},
//     {company: "Raytheon", symbol: "RTN"},
//     {company: "Plains GP Holdings", symbol: "PAGP"},
//     {company: "US Foods", symbol: ""},
//     {company: "AbbVie", symbol: "ABBV"},
//     {company: "Centene", symbol: "CNC"},
//     {company: "Community Health Systems", symbol: "CYH"},
//     {company: "Arconic", symbol: "ARNC"},
//     {company: "International Paper", symbol: "IP"},
//     {company: "Emerson Electric", symbol: "EMR"},
//     {company: "Union Pacific", symbol: "UNP"},
//     {company: "Amgen", symbol: "AMGN"},
//     {company: "U.S. Bancorp", symbol: "USB"},
//     {company: "Staples", symbol: "SPLS"},
//     {company: "Danaher", symbol: "DHR"},
//     {company: "Whirlpool", symbol: "WHR"},
//     {company: "Aflac", symbol: "AFL"},
//     {company: "AutoNation", symbol: "AN"},
//     {company: "Progressive", symbol: "PGR"},
//     {company: "Abbott Laboratories", symbol: "ABT"},
//     {company: "Dollar General", symbol: "DG"},
//     {company: "Tenet Healthcare", symbol: "THC"},
//     {company: "Eli Lilly", symbol: "LLY"},
//     {company: "Southwest Airlines", symbol: "LUV"},
//     {company: "Penske Automotive Group", symbol: "PAG"},
//     {company: "ManpowerGroup", symbol: "MAN"},
//     {company: "Kohl's", symbol: "KSS"},
//     {company: "Starbucks", symbol: "SBUX"},
//     {company: "Paccar", symbol: "PCAR"},
//     {company: "Cummins", symbol: "CMI"},
//     {company: "Altria Group", symbol: "MO"},
//     {company: "Xerox", symbol: "XRX"},
//     {company: "Kimberly-Clark", symbol: "KMB"},
//     {company: "Hartford Financial Services Group", symbol: "HIG"},
//     {company: "Kraft Heinz", symbol: "KHC"},
//     {company: "Lear", symbol: "LEA"},
//     {company: "Fluor", symbol: "FLR"},
//     {company: "AECOM", symbol: "ACM"},
//     {company: "Facebook", symbol: "FB"},
//     {company: "Jabil Circuit", symbol: "JBL"},
//     {company: "CenturyLink", symbol: "CTL"},
//     {company: "Supervalu", symbol: "SVU"},
//     {company: "General Mills", symbol: "GIS"},
//     {company: "Southern", symbol: "SO"},
//     {company: "NextEra Energy", symbol: "NEE"},
//     {company: "Thermo Fisher Scientific", symbol: "TMO"},
//     {company: "American Electric Power", symbol: "AEP"},
//     {company: "PG&E Corp.", symbol: "PCG"},
//     {company: "NGL Energy Partners", symbol: "NGL"},
//     {company: "Bristol-Myers Squibb", symbol: "BMY"},
//     {company: "Goodyear Tire & Rubber", symbol: "G"},
//     {company: "Nucor", symbol: "NUE"},
//     {company: "PNC Financial Services Group", symbol: "PNC"},
//     {company: "Health Net", symbol: "HNT"},
//     {company: "Micron Technology", symbol: "MU"},
//     {company: "Colgate-Palmolive", symbol: "CL"},
//     {company: "Freeport-McMoRan", symbol: "FCX"},
//     {company: "ConAgra Foods", symbol: "CAG"},
//     {company: "Gap", symbol: "GPS"},
//     {company: "Baker Hughes", symbol: "BHI"},
//     {company: "Bank of New York Mellon Corp.", symbol: "BK"},
//     {company: "Dollar Tree", symbol: "DLTR"},
//     {company: "Whole Foods Market", symbol: "WFM"},
//     {company: "PPG Industries", symbol: "PPG"},
//     {company: "Genuine Parts", symbol: "GPC"},
//     {company: "Icahn Enterprises", symbol: "IEP"},
//     {company: "Performance Food Group", symbol: "PFGC"},
//     {company: "Omnicom Group", symbol: "OMC"},
//     {company: "DISH Network", symbol: "DISH"},
//     {company: "FirstEnergy", symbol: "FE"},
//     {company: "Monsanto", symbol: "MON"},
//     {company: "AES", symbol: "AES"},
//     {company: "CarMax", symbol: "KMX"},
//     {company: "National Oilwell Varco", symbol: "NO8"},
//     {company: "NRG Energy", symbol: "NRG"},
//     {company: "Western Digital", symbol: "WDC"},
//     {company: "Marriott International", symbol: "MAR"},
//     {company: "Office Depot", symbol: "ODP"},
//     {company: "Nordstrom", symbol: "JWN"},
//     {company: "Kinder Morgan", symbol: "KMI"},
//     {company: "Aramark", symbol: "ARMK"},
//     {company: "DaVita", symbol: "DVA"},
//     {company: "Molina Healthcare", symbol: "MOH"},
//     {company: "WellCare Health Plans", symbol: "WCG"},
//     {company: "CBS", symbol: "CBS"},
//     {company: "Visa", symbol: "V"},
//     {company: "Lincoln National", symbol: "LNC"},
//     {company: "Ecolab", symbol: "ECL"},
//     {company: "Kellogg", symbol: "K"},
//     {company: "C.H. Robinson Worldwide", symbol: "CHRW"},
//     {company: "Textron", symbol: "TXT"},
//     {company: "Loews", symbol: "L"},
//     {company: "Illinois Tool Works", symbol: "ITW"},
//     {company: "Synnex", symbol: "SNX"},
//     {company: "Viacom", symbol: "VIAB"},
//     {company: "HollyFrontier", symbol: "HFC"},
//     {company: "Land O'Lakes", symbol: "LAKE"},
//     {company: "Devon Energy", symbol: "DVN"},
//     {company: "PBF Energy", symbol: "PBF"},
//     {company: "Yum Brands", symbol: "YUM"},
//     {company: "Texas Instruments", symbol: "TXN"},
//     {company: "CDW", symbol: "CDW"},
//     {company: "Waste Management", symbol: "WM"},
//     {company: "Marsh & McLennan", symbol: "MMC"},
//     {company: "Chesapeake Energy", symbol: "CHK"},
//     {company: "Parker-Hannifin", symbol: "PH"},
//     {company: "Occidental Petroleum", symbol: "OXY"},
//     {company: "Guardian Life Ins. Co. of America", symbol: ""},
//     {company: "Farmers Insurance Exchange", symbol: ""},
//     {company: "J.C. Penney", symbol: "JCP"},
//     {company: "Consolidated Edison", symbol: "ED"},
//     {company: "Cognizant Technology Solutions", symbol: "CTSH"},
//     {company: "VF", symbol: "VFC"},
//     {company: "Ameriprise Financial", symbol: "AMP"},
//     {company: "Computer Sciences", symbol: "CSC"},
//     {company: "L Brands", symbol: "LB"},
//     {company: "Jacobs Engineering Group", symbol: "JEC"},
//     {company: "Principal Financial Group", symbol: "PFG"},
//     {company: "Ross Stores", symbol: "ROST"},
//     {company: "Bed Bath & Beyond", symbol: "BBBY"},
//     {company: "CSX", symbol: "CSX"},
//     {company: "Toys ", symbol: "TOY"},
//     {company: "Las Vegas Sands", symbol: "LVS"},
//     {company: "Leucadia National", symbol: "LUK"},
//     {company: "Dominion Resources", symbol: "D"},
//     {company: "United States Steel", symbol: "X"},
//     {company: "L-3 Communications", symbol: "LLL"},
//     {company: "Edison International", symbol: "EIX"},
//     {company: "Entergy", symbol: "ELA"},
//     {company: "ADP", symbol: "ADP"},
//     {company: "First Data", symbol: "FDC"},
//     {company: "BlackRock", symbol: "BLK"},
//     {company: "WestRock", symbol: "WRK"},
//     {company: "Voya Financial", symbol: "VOYA"},
//     {company: "Sherwin-Williams", symbol: "SHW"},
//     {company: "Hilton Worldwide Holdings", symbol: "HLT"},
//     {company: "R.R. Donnelley & Sons", symbol: "RRD"},
//     {company: "Stanley Black & Decker", symbol: "SWK"},
//     {company: "Xcel Energy", symbol: "XEL"},
//     {company: "Murphy USA", symbol: "MUSA"},
//     {company: "CBRE Group", symbol: "CBG"},
//     {company: "D.R. Horton", symbol: "DHI"},
//     {company: "Estee Lauder", symbol: "EL"},
//     {company: "Praxair", symbol: "PX"},
//     {company: "Biogen", symbol: "BIIB"},
//     {company: "State Street Corp.", symbol: "STT"},
//     {company: "Unum Group", symbol: "UNM"},
//     {company: "Reynolds American", symbol: "RAI"},
//     {company: "Group 1 Automotive", symbol: "GPI"},
//     {company: "Henry Schein", symbol: "HSIC"},
//     {company: "Hertz Global Holdings", symbol: "HRI"},
//     {company: "Norfolk Southern", symbol: "NSC"},
//     {company: "Reinsurance Group of America", symbol: "RGA"},
//     {company: "Public Service Enterprise Group", symbol: "PEG"},
//     {company: "BB&T Corp.", symbol: "BBT"},
//     {company: "DTE Energy", symbol: "DTE"},
//     {company: "Assurant", symbol: "AIZ"},
//     {company: "Global Partners", symbol: "GLP"},
//     {company: "Huntsman", symbol: "HUN"},
//     {company: "Becton Dickinson", symbol: "BDX"},
//     {company: "Sempra Energy", symbol: "SRE"},
//     {company: "AutoZone", symbol: "AZO"},
//     {company: "Navistar International", symbol: "NAV"},
//     {company: "Precision Castparts", symbol: "PCP"},
//     {company: "Discover Financial Services", symbol: "DFS"},
//     {company: "Liberty Interactive", symbol: "QVCA"},
//     {company: "W.W. Grainger", symbol: "GWW"},
//     {company: "Baxter International", symbol: "BAX"},
//     {company: "Stryker", symbol: "SYK"},
//     {company: "Air Products & Chemicals", symbol: "APD"},
//     {company: "Western Refining", symbol: "WNR"},
//     {company: "Universal Health Services", symbol: "UHS"},
//     {company: "Owens & Minor", symbol: "OMI"},
//     {company: "Charter Communications", symbol: "CHTR"},
//     {company: "Advance Auto Parts", symbol: "AAP"},
//     {company: "MasterCard", symbol: "MA"},
//     {company: "Applied Materials", symbol: "AMAT"},
//     {company: "Eastman Chemical", symbol: "EMN"},
//     {company: "Sonic Automotive", symbol: "SAH"},
//     {company: "Ally Financial", symbol: "ALLY"},
//     {company: "CST Brands", symbol: "CST"},
//     {company: "eBay", symbol: "EBAY"},
//     {company: "Lennar", symbol: "LEN"},
//     {company: "GameStop", symbol: "GME"},
//     {company: "Reliance Steel & Aluminum", symbol: "RS"},
//     {company: "Hormel Foods", symbol: "HRL"},
//     {company: "Celgene", symbol: "CELG"},
//     {company: "Genworth Financial", symbol: "GNW"},
//     {company: "PayPal Holdings", symbol: "PYPL"},
//     {company: "Priceline Group", symbol: "PCLN"},
//     {company: "MGM Resorts International", symbol: "MGM"},
//     {company: "Autoliv", symbol: "ALV"},
//     {company: "Fidelity National Financial", symbol: "FNF"},
//     {company: "Republic Services", symbol: "RSG"},
//     {company: "Corning", symbol: "GLW"},
//     {company: "Peter Kiewit Sons'", symbol: ""},
//     {company: "Univar", symbol: "UNVR"},
//     {company: "Mosaic", symbol: "MOS"},
//     {company: "Core-Mark Holding", symbol: "CORE"},
//     {company: "Thrivent Financial for Lutherans", symbol: ""},
//     {company: "Cameron International", symbol: "CAM"},
//     {company: "HD Supply Holdings", symbol: "HDS"},
//     {company: "Crown Holdings", symbol: "CCK"},
//     {company: "EOG Resources", symbol: "EOG"},
//     {company: "Veritiv", symbol: "VRTV"},
//     {company: "Anadarko Petroleum", symbol: "APC"},
//     {company: "Laboratory Corp. of America", symbol: "LH"},
//     {company: "Pacific Life", symbol: ""},
//     {company: "News Corp.", symbol: "FOXA"},
//     {company: "Jarden", symbol: "JAH"},
//     {company: "SunTrust Banks", symbol: "STI"},
//     {company: "Avis Budget Group", symbol: "CAR"},
//     {company: "Broadcom", symbol: "BRCM"},
//     {company: "American Family Insurance Group", symbol: ""},
//     {company: "Level 3 Communications", symbol: "LVLT"},
//     {company: "Tenneco", symbol: "TEN"},
//     {company: "United Natural Foods", symbol: "UNFI"},
//     {company: "Dean Foods", symbol: "DF"},
//     {company: "Campbell Soup", symbol: "CPB"},
//     {company: "Mohawk Industries", symbol: "MHK"},
//     {company: "BorgWarner", symbol: "BWA"},
//     {company: "PVH", symbol: "PVH"},
//     {company: "Ball", symbol: "BLL"},
//     {company: "O'Reilly Automotive", symbol: "ORLY"},
//     {company: "Eversource Energy", symbol: "ES"},
//     {company: "Franklin Resources", symbol: "BEN"},
//     {company: "Masco", symbol: "MAS"},
//     {company: "Lithia Motors", symbol: "LAD"},
//     {company: "KKR", symbol: "KKR"},
//     {company: "Oneok", symbol: "OKE"},
//     {company: "Newmont Mining", symbol: "NEM"},
//     {company: "PPL", symbol: "PPL"},
//     {company: "SpartanNash", symbol: "SPTN"},
//     {company: "Quanta Services", symbol: "PWR"},
//     {company: "XPO Logistics", symbol: "XPO"},
//     {company: "Ralph Lauren", symbol: "RL"},
//     {company: "Interpublic Group", symbol: "IPG"},
//     {company: "Steel Dynamics", symbol: "STLD"},
//     {company: "WESCO International", symbol: "WCC"},
//     {company: "Quest Diagnostics", symbol: "DGX"},
//     {company: "Boston Scientific", symbol: "BSX"},
//     {company: "AGCO", symbol: "AGCO"},
//     {company: "Foot Locker", symbol: "FL"},
//     {company: "Hershey", symbol: "HSY"},
//     {company: "CenterPoint Energy", symbol: "CNP"},
//     {company: "Williams", symbol: "WMB"},
//     {company: "Dick's Sporting Goods", symbol: "DKS"},
//     {company: "Live Nation Entertainment", symbol: "LYV"},
//     {company: "Mutual of Omaha Insurance", symbol: ""},
//     {company: "W.R. Berkley", symbol: "WRB"},
//     {company: "LKQ", symbol: "LKQ"},
//     {company: "Avon Products", symbol: "AVP"},
//     {company: "Darden Restaurants", symbol: "DRI"},
//     {company: "Kindred Healthcare", symbol: "KND"},
//     {company: "Weyerhaeuser", symbol: "WY"},
//     {company: "Casey's General Stores", symbol: "CASY"},
//     {company: "Sealed Air", symbol: "SEE"},
//     {company: "Fifth Third Bancorp", symbol: "FITB"},
//     {company: "Dover", symbol: "DOV"},
//     {company: "Huntington Ingalls Industries", symbol: "HII"},
//     {company: "Netflix", symbol: "NFLX"},
//     {company: "Dillard's", symbol: "DDS"},
//     {company: "EMCOR Group", symbol: "EME"},
//     {company: "Jones Financial", symbol: "JONE"},
//     {company: "AK Steel Holding", symbol: "AKS"},
//     {company: "UGI", symbol: "UGI"},
//     {company: "Expedia", symbol: "EXPE"},
//     {company: "salesforce.com", symbol: "CRM"},
//     {company: "Targa Resources", symbol: "TRGP"},
//     {company: "Apache", symbol: "APA"},
//     {company: "Spirit AeroSystems Holdings", symbol: "SPR"},
//     {company: "Expeditors International of Washington", symbol: "EXPD"},
//     {company: "Anixter International", symbol: "AXE"},
//     {company: "Fidelity National Information Services", symbol: "FIS"},
//     {company: "Asbury Automotive Group", symbol: "ABG"},
//     {company: "Hess", symbol: "HES"},
//     {company: "Ryder System", symbol: "R"},
//     {company: "Terex", symbol: "TEX"},
//     {company: "Coca-Cola European Partners", symbol: ""},
//     {company: "Auto-Owners Insurance", symbol: ""},
//     {company: "Cablevision Systems", symbol: "CVC"},
//     {company: "Symantec", symbol: "SYMC"},
//     {company: "Charles Schwab", symbol: "SCHW"},
//     {company: "Calpine", symbol: "CPN"},
//     {company: "CMS Energy", symbol: "CMS"},
//     {company: "Alliance Data Systems", symbol: "ADS"},
//     {company: "JetBlue Airways", symbol: "JBLU"},
//     {company: "Discovery Communications", symbol: "DISCA"},
//     {company: "Trinity Industries", symbol: "TRN"},
//     {company: "Sanmina", symbol: "SANM"},
//     {company: "NCR", symbol: "NCR"},
//     {company: "FMC Technologies", symbol: "FTI"},
//     {company: "Erie Insurance Group", symbol: "ERIE"},
//     {company: "Rockwell Automation", symbol: "ROK"},
//     {company: "Dr Pepper Snapple Group", symbol: "DPS"},
//     {company: "iHeartMedia", symbol: "IHRT"},
//     {company: "Tractor Supply", symbol: "TSCO"},
//     {company: "J.B. Hunt Transport Services", symbol: "JBHT"},
//     {company: "Commercial Metals", symbol: "CMC"},
//     {company: "Owens-Illinois", symbol: "OI"},
//     {company: "Harman International Industries", symbol: "HAR"},
//     {company: "Baxalta", symbol: "BXLT"},
//     {company: "American Financial Group", symbol: "AFG"},
//     {company: "NetApp", symbol: "NTAP"},
//     {company: "Graybar Electric", symbol: ""},
//     {company: "Oshkosh", symbol: "OSK"},
//     {company: "Ameren", symbol: "AEE"},
//     {company: "A-Mark Precious Metals", symbol: "AMRK"},
//     {company: "Barnes & Noble", symbol: "BKS"},
//     {company: "Dana Holding", symbol: "DAN"},
//     {company: "Constellation Brands", symbol: "STZ"},
//     {company: "LifePoint Health", symbol: "LPNT"},
//     {company: "Zimmer Biomet Holdings", symbol: "ZBH"},
//     {company: "Harley-Davidson", symbol: "HOG"},
//     {company: "PulteGroup", symbol: "PHM"},
//     {company: "Newell Brands", symbol: "NWL"},
//     {company: "Avery Dennison", symbol: "AVY"},
//     {company: "Jones Lang LaSalle", symbol: "JLL"},
//     {company: "WEC Energy Group", symbol: "WEC"},
//     {company: "Marathon Oil", symbol: "MRO"},
//     {company: "TravelCenters of America", symbol: "TA"},
//     {company: "United Rentals", symbol: "URI"},
//     {company: "HRG Group", symbol: "HRG"},
//     {company: "Old Republic International", symbol: "ORI"},
//     {company: "Windstream Holdings", symbol: "WIN"},
//     {company: "Starwood Hotels & Resorts", symbol: "HOT"},
//     {company: "Delek US Holdings", symbol: "DK"},
//     {company: "Packaging Corp. of America", symbol: "PKG"},
//     {company: "Quintiles IMS Holdings", symbol: "Q"},
//     {company: "Hanesbrands", symbol: "HBI"},
//     {company: "Realogy Holdings", symbol: "RLGY"},
//     {company: "Mattel", symbol: "MAT"},
//     {company: "Motorola Solutions", symbol: "MSI"},
//     {company: "J.M. Smucker", symbol: "SJM"},
//     {company: "Regions Financial", symbol: "RF"},
//     {company: "Celanese", symbol: "CE"},
//     {company: "Clorox", symbol: "CLX"},
//     {company: "Ingredion", symbol: "INGR"},
//     {company: "Genesis Healthcare", symbol: "GEN"},
//     {company: "Peabody Energy", symbol: "BTU"},
//     {company: "Alaska Air Group", symbol: "ALK"},
//     {company: "Seaboard", symbol: "SEB"},
//     {company: "Frontier Communications", symbol: "FTR"},
//     {company: "Amphenol", symbol: "APH"},
//     {company: "Lansing Trade Group", symbol: ""},
//     {company: "SanDisk", symbol: "SNDK"},
//     {company: "St. Jude Medical", symbol: "STJ"},
//     {company: "Wyndham Worldwide", symbol: "WYN"},
//     {company: "Kelly Services", symbol: "KELYA"},
//     {company: "Western Union", symbol: "WU"},
//     {company: "Envision Healthcare Holdings", symbol: ""},
//     {company: "Visteon", symbol: "VC"},
//     {company: "Arthur J. Gallagher", symbol: "AJG"},
//     {company: "Host Hotels & Resorts", symbol: "HST"},
//     {company: "Ashland", symbol: "ASH"},
//     {company: "Insight Enterprises", symbol: "NSIT"},
//     {company: "Energy Future Holdings", symbol: ""},
//     {company: "Markel", symbol: "MKL"},
//     {company: "Essendant", symbol: "ESND"},
//     {company: "CH2M Hill", symbol: ""},
//     {company: "Western & Southern Financial Group", symbol: ""},
//     {company: "Owens Corning", symbol: "OC"},
//     {company: "S&P Global", symbol: "SPGI"},
//     {company: "Raymond James Financial", symbol: "RJF"},
//     {company: "NiSource", symbol: "NI"},
//     {company: "Airgas", symbol: "ARG"},
//     {company: "ABM Industries", symbol: "ABM"},
//     {company: "Citizens Financial Group", symbol: "CFG"},
//     {company: "Booz Allen Hamilton Holding", symbol: "BAH"},
//     {company: "Simon Property Group", symbol: "SPGI"},
//     {company: "Domtar", symbol: "UFS"},
//     {company: "Rockwell Collins", symbol: "COL"},
//     {company: "Lam Research", symbol: "LRCX"},
//     {company: "Fiserv", symbol: "FISV"},
//     {company: "Spectra Energy", symbol: "SE"},
//     {company: "Navient", symbol: "NAVI"},
//     {company: "Big Lots", symbol: "BIG"},
//     {company: "Telephone & Data Systems", symbol: "TDS"},
//     {company: "First American Financial", symbol: "FAF"},
//     {company: "NVR", symbol: "NVR"},
//     {company: "Cincinnati Financial", symbol: "CINF"},
//     {company: "Burlington Stores", symbol: "BURL"}
//   ]

module.exports = tickers;