export const categories = [
    {id:1, value:"Transportation",label:"Transportation"},
    {id:2, value:"Food",label:"Food"},
    {id:3, value:"Utilities",label:"Utilities"},
    {id:4, value:"Social",label:"Social"},
    {id:5, value:"Clothing",label:"Clothing"},
    {id:6, value:"Medical",label:"Medical"},
    {id:7, value:"Health",label:"Health"},
    {id:8, value:"Beauty",label:"Beauty"},
    {id:9, value:"Insurance",label:"Insurance"},
    {id:10, value:"Personal",label:"Personal"},
    {id:11, value:"Debt",label:"Debt"},
    {id:12, value:"Retirement",label:"Retirement"},
    {id:13, value:"Savings",label:"Savings"},
    {id:14, value:"Education",label:"Education"},
    {id:15, value:"Giving",label:"Giving"},
    {id:16, value:"Taxes",label:"Taxes"},
    {id:17, value:"Investments",label:"Investments"},
    {id:18, value:"Hobbies",label:"Hobbies"},
    {id:19, value:"Pets",label:"Pets"},
    {id:20, value:"Other",label:"Other"}
];

export const subcategories = [
    { id:1,parent:"Transportation",value: 'Gas', label: 'Gas' },
    { id:2,parent:"Transportation",value: 'Car Payment', label: 'Car Payment' },
    { id:3,parent:"Transportation",value: 'Maintenance/Oil Change', label: 'Maintenance/Oil Change' },
    { id:4,parent:"Transportation",value: 'Repairs', label: 'Repairs' },
    { id:5,parent:"Transportation",value: 'Tires', label: 'Tires' },
    { id:6,parent:"Transportation",value: 'DMV', label: 'DMV' },
    { id:7,parent:"Food",value: 'Groceries', label: 'Groceries' },
    { id:8,parent:"Food",value: 'Restaurants', label: 'Restaurants' },
    { id:9,parent:"Food",value: 'Pet Food', label: 'Pet Food' },
    { id:10,parent:"Utilities",value: 'Electricity', label: 'Electricity' },
];
